services:
    label-studio:
        image: heartexlabs/label-studio:latest
        container_name: label-studio
        ports:
            - '8080:8080'
        environment:
            - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
            - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
        volumes:
            # 1) Your roblox-avatar-data lives here for import
            - ./roblox-avatar-data:/label-studio/files/roblox-avatar-data
            # 2) Label Studio’s internal data (DB + uploads) lives here
            - ./labelstudio_data:/label-studio/data
        restart: unless-stopped
